image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.test.skip=true"


cache:
  key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
  paths:
    - .m2/repository/
    - target/

stages:
  - build

build:
  stage: build
  before_script:
    - ls -lha
    - mkdir -p /root/.m2
    - touch /root/.m2/settings-security.xml
    - echo "<settingsSecurity><master>${MAVEN_MASTER_PASSWORD}</master></settingsSecurity>" > /root/.m2/settings-security.xml

  script:
    - ls -lha
    - mvn $MAVEN_CLI_OPTS -Pspark-2.2-scala-2.11 compile
    - mvn $MAVEN_CLI_OPTS -Pspark-2.2-scala-2.11 deploy
